lista =["Karolina Nawara" ,
        "Marcin Brzezicki",
        "Patrycja Gielata" ,
        "Wojtek Kaleta" ,
        "Wiesław Horwacik",
        "Józef Wróbel",
        "Tadeusz Bałos",
        "Aleksandra Mistarz",
        "Łukasz Mirek",
        "Kuba Chryc",
        "Michał Kluska",
        "Radek Książek",
"Marcin Książek",
"Marianna Puneyko",
"Pati Gospodarczyk",
"Sebastian Talaga",
"Dawid Chryc",
"Tomek Dańczak",
"Julia Czyszczoń",
"Sylwia Kaletka",
"Patrycja Kaletka",
"Adrian Kruźlak",
"Kuba Kluska",
"Iwona Szopa",
"Kamil Szopa",
"Anka Brzezicka",
"Karolina Bierówka",
"Darek Mirek",
"Klaudia Pustelnik",
"Robert Kołodziej",
"Aneta Zięcina",
"Tadeusz Mizera",
"Gabriela Jończyk",
"Magda Mizera",
"Dawid Stopa",
"Tomasz Romaniak",
"Krzysiek Horwacik",
"Kacper Wójcicki",
"Sławek Kosek",
"Dominika Gierat",
"Dawid Filipek",
"Paweł Bubiak",
"Wiki Bagadzińska",
"Szymon Kołodziej",
"Tomasz Jątyka",
"Beata Mizera",
"Patryk Pindel",
"Magda Poznańska-Książek",
"Kamil Dziubras",
"Michał Cieżak",
"Tomek Górni",
"Piotr Jan Ożarowski",
"Agata Marczewska",
"Maciej Bierówka",
"Grzesiek Książek",
        "Joanna Szopa" ,
        "Łukasz Ożarowski" ,
        "Justyna Hanusiak" ,
        "Wiktor Kołodziejczyk" ,
        "Osoba Towarzyszaca Jatyki"]